"""game usernames

Revision ID: 35942d8372ad
Revises: d16a57ca3ff8
Create Date: 2025-06-13 08:35:33.667698

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35942d8372ad'
down_revision: Union[str, None] = 'd16a57ca3ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('white_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game', sa.Column('black_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_constraint(op.f('playermetrics_username_key'), 'playermetrics', type_='unique')
    op.drop_column('playermetrics', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playermetrics', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_unique_constraint(op.f('playermetrics_username_key'), 'playermetrics', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_column('game', 'black_username')
    op.drop_column('game', 'white_username')
    # ### end Alembic commands ###
