"""add move_times

Revision ID: 84bc834f99a3
Revises: 60adad4ee42c
Create Date: 2025-04-19 18:33:55.897668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84bc834f99a3'
down_revision: Union[str, None] = '60adad4ee42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('move_times', sa.JSON(), nullable=True))
    op.add_column('gamemetrics', sa.Column('sigma_total', sa.Float(), nullable=True))
    op.add_column('gamemetrics', sa.Column('constant_time', sa.Boolean(), nullable=False))
    op.add_column('gamemetrics', sa.Column('pause_spike', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('gamemetrics', 'pause_spike')
    op.drop_column('gamemetrics', 'constant_time')
    op.drop_column('gamemetrics', 'sigma_total')
    op.drop_column('game', 'move_times')
    # ### end Alembic commands ###
