"""opening fields

Revision ID: 918a2090423b
Revises: 84bc834f99a3
Create Date: 2025-06-05 08:15:15.145601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel                     # ←  AÑADE ESTA LÍNEA


# revision identifiers, used by Alembic.
revision: str = '918a2090423b'
down_revision: Union[str, None] = '84bc834f99a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playermetrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_count', sa.Integer(), nullable=False),
    sa.Column('opening_entropy', sa.Float(), nullable=False),
    sa.Column('most_played', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('low_entropy', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('game', sa.Column('eco_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('game', sa.Column('opening_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'opening_key')
    op.drop_column('game', 'eco_code')
    op.drop_table('playermetrics')
    # ### end Alembic commands ###
