"""add game_metrics

Revision ID: a9268f732656
Revises: 7ed3cdf06fe7
Create Date: 2025-04-19 13:25:39.195387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a9268f732656'
down_revision: Union[str, None] = '7ed3cdf06fe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('pgn', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gamemetrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('pct_top1', sa.Float(), nullable=False),
    sa.Column('pct_top3', sa.Float(), nullable=False),
    sa.Column('acl', sa.Float(), nullable=False),
    sa.Column('suspicious', sa.Boolean(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_table('moveanalysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('played', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('best', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('best_rank', sa.Integer(), nullable=False),
    sa.Column('cp_loss', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moveanalysis')
    op.drop_table('gamemetrics')
    op.drop_table('game')
    # ### end Alembic commands ###
