"""add_player_usernames

Revision ID: b7962b0770e6
Revises: b7313656d818
Create Date: 2025-07-09 14:24:39.222359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7962b0770e6'
down_revision: Union[str, None] = 'b7313656d818'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('white_username', sa.String(), nullable=True))
    op.add_column('game', sa.Column('black_username', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'black_username')
    op.drop_column('game', 'white_username')
    # ### end Alembic commands ###
