"""player counters

Revision ID: ebd2464e2e9d
Revises: 35942d8372ad
Create Date: 2025-06-13 09:08:41.373327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd2464e2e9d'
down_revision: Union[str, None] = '35942d8372ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('total_games', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('done_games', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'done_games')
    op.drop_column('player', 'total_games')
    # ### end Alembic commands ###
